support darwin-arm64

diff --git a/build b/build
--- a/build
+++ b/build
@@ -132,17 +132,20 @@ case "$TMUX_BIN_KERNEL" in
       >&2 echo "[error] please run 'xcode-select --install' and retry"
       exit 1
     fi
-    if ! command -v brew >/dev/null 2>&1; then
-      >&2 echo "[error] please install homebrew from https://brew.sh/ and retry"
+    if command -v port >/dev/null 2>&1; then
+      sudo port -N install autoconf automake wget libevent bison
+    elif command -v brew >/dev/null 2>&1; then
+      for formula in autoconf automake wget libevent bison pkg-config utf8proc; do
+        if brew ls --version "$formula" >/dev/null; then
+          brew upgrade "$formula"
+        else
+          brew install "$formula"
+        fi
+      done
+    else
+      >&2 echo "[error] please install MacPorts or Homebrew and retry"
       exit 1
     fi
-    for formula in autoconf automake wget libevent bison pkg-config utf8proc; do
-      if brew ls --version "$formula" >/dev/null; then
-        brew upgrade "$formula"
-      else
-        brew install "$formula"
-      fi
-    done
   ;;
   *)
     >&2 echo "[internal error] unhandled kernel: $TMUX_BIN_KERNEL"
@@ -214,12 +217,19 @@ case "$TMUX_BIN_KERNEL" in
     tmux_configure_flags="$tmux_configure_flags --enable-static"
   ;;
   darwin)
-    opt=/usr/local/opt
     mkdir -- "$workdir"/lib
-    ln -s -- "$opt"/libevent/lib/libevent.a "$opt"/utf8proc/lib/libutf8proc.a "$workdir"/lib
-    CFLAGS="$CFLAGS -I$opt/libevent/include -I$opt/utf8proc/include"
-    LDFLAGS="$LDFLAGS -L$workdir/lib"
-    tmux_configure_flags="$tmux_configure_flags --enable-utf8proc"
+    if [ -e /opt/local/lib/libevent.a ]; then
+      ln -s -- /opt/local/lib/libevent.a "$workdir"/lib
+      CFLAGS="$CFLAGS -I/opt/local/include"
+      LDFLAGS="$LDFLAGS -L/opt/local/lib"
+      # TODO: use utf8proc.
+    else
+      opt=/usr/local/opt
+      ln -s -- "$opt"/libevent/lib/libevent.a "$opt"/utf8proc/lib/libutf8proc.a "$workdir"/lib
+      CFLAGS="$CFLAGS -I$opt/libevent/include -I$opt/utf8proc/include"
+      LDFLAGS="$LDFLAGS -L$workdir/lib"
+      tmux_configure_flags="$tmux_configure_flags --enable-utf8proc"
+    fi
   ;;
   *)
     >&2 echo "[internal error] unhandled kernel: $TMUX_BIN_KERNEL"
@@ -350,6 +360,7 @@ if [ -z "$TMUX_BIN_CPU" ]; then
   case "$TMUX_BIN_ARCH" in
     armv6l)         TMUX_BIN_CPU=armv6;;
     armv7l)         TMUX_BIN_CPU=armv7;;
+    arm64)          TMUX_BIN_CPU=armv8;;
     aarch64)        TMUX_BIN_CPU=armv8-a;;
     ppc64le)        TMUX_BIN_CPU=powerpc64le;;
     x86_64|amd64)   TMUX_BIN_CPU=x86-64;;
